field.widget.settings.page_builder_entity_reference_paragraphs:
  type: mapping
  label: 'Add page builder elements'
  mapping:
    title:
      type: label
    title_plural:
      type: label
    edit_mode:
      type: string
    add_mode:
      type: string
    form_display_mode:
      type: string
    default_paragraph_type:
      type: string
